# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=18, verbose_name='\u5e74\u9f84'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_years',
            field=models.IntegerField(default=0, verbose_name='\u5de5\u4f5c\u5e74\u9650'),
        ),
    ]
